export default [
  "dz",
  "ao",
  "bj",
  "bw",
  "bf",
  "bi",
  "cv",
  "cm",
  "cf",
  "td",
  "km",
  "cg",
  "cd",
  "ci",
  "dj",
  "eg",
  "gq",
  "er",
  "sz",
  "et",
  "ga",
  "gm",
  "gh",
  "gn",
  "gw",
  "ke",
  "ls",
  "lr",
  "ly",
  "mg",
  "mw",
  "ml",
  "mr",
  "mu",
  "yt",
  "ma",
  "mz",
  "na",
  "ne",
  "ng",
  "re",
  "rw",
  "st",
  "sn",
  "sc",
  "sl",
  "so",
  "za",
  "ss",
  "sd",
  "tz",
  "tg",
  "tn",
  "ug",
  "eh",
  "zm",
  "zw",
];

export const countries = [
  {
    iso: "ad",
    code: "EUR",
    symbol: "€",
    capital: "Andorra la Vella",
    continent: "Europe",
  },
  {
    iso: "ae",
    code: "AED",
    symbol: "د.إ",
    capital: "Abu Dhabi",
    continent: "Asia",
  },
  {
    iso: "af",
    code: "AFN",
    symbol: "Afs",
    capital: "Kabul",
    continent: "Asia",
  },
  {
    iso: "ag",
    code: "XCD",
    symbol: "$",
    capital: "St. John's",
    continent: "North America",
  },
  {
    iso: "ai",
    code: "XCD",
    symbol: "$",
    capital: "The Valley",
    continent: "North America",
  },
  {
    iso: "al",
    code: "ALL",
    symbol: "L",
    capital: "Tirana",
    continent: "Europe",
  },
  {
    iso: "am",
    code: "AMD",
    symbol: "AMD",
    capital: "Yerevan",
    continent: "Asia",
  },
  {
    iso: "ao",
    code: "AOA",
    symbol: "Kz",
    capital: "Luanda",
    continent: "Africa",
  },
  {
    iso: "ar",
    code: "ARS",
    symbol: "$",
    capital: "Buenos Aires",
    continent: "South America",
  },
  {
    iso: "as",
    code: "USD",
    symbol: "$",
    capital: "Pago Pago",
    continent: "Oceania",
  },
  {
    iso: "at",
    code: "EUR",
    symbol: "€",
    capital: "Vienna",
    continent: "Europe",
  },
  {
    iso: "au",
    code: "AUD",
    symbol: "$",
    capital: "Canberra",
    continent: "Oceania",
  },
  {
    iso: "aw",
    code: "AWG",
    symbol: "ƒ",
    capital: "Oranjestad",
    continent: "North America",
  },
  {
    iso: "ax",
    code: "EUR",
    symbol: "€",
    capital: "Mariehamn",
    continent: "Europe",
  },
  {
    iso: "az",
    code: "AZN",
    symbol: "AZN",
    capital: "Baku",
    continent: "Asia",
  },
  {
    iso: "ba",
    code: "BAM",
    symbol: "KM",
    capital: "Sarajevo",
    continent: "Europe",
  },
  {
    iso: "bb",
    code: "BBD",
    symbol: "Bds$",
    capital: "Bridgetown",
    continent: "North America",
  },
  {
    iso: "bd",
    code: "BDT",
    symbol: "৳",
    capital: "Dhaka",
    continent: "Asia",
  },
  {
    iso: "be",
    code: "EUR",
    symbol: "€",
    capital: "Brussels",
    continent: "Europe",
  },
  {
    iso: "bf",
    code: "XOF",
    symbol: "CFA",
    capital: "Ouagadougou",
    continent: "Africa",
  },
  {
    iso: "bg",
    code: "BGN",
    symbol: "BGN",
    capital: "Sofia",
    continent: "Europe",
  },
  {
    iso: "bh",
    code: "BHD",
    symbol: ".د.ب",
    capital: "Manama",
    continent: "Asia",
  },
  {
    iso: "bi",
    code: "BIF",
    symbol: "FBu",
    capital: "Bujumbura",
    continent: "Africa",
  },
  {
    iso: "bj",
    code: "XOF",
    symbol: "CFA",
    capital: "Porto-Novo",
    continent: "Africa",
  },
  {
    iso: "bl",
    code: "EUR",
    symbol: "€",
    capital: "Gustavia",
    continent: "North America",
  },
  {
    iso: "bm",
    code: "BMD",
    symbol: "BD$",
    capital: "Hamilton",
    continent: "North America",
  },
  {
    iso: "bn",
    code: "BND",
    symbol: "B$",
    capital: "Bandar Seri Begawan",
    continent: "Asia",
  },
  {
    iso: "bo",
    code: "BOB",
    symbol: "Bs.",
    capital: "Sucre",
    continent: "South America",
  },
  {
    iso: "bq",
    code: "USD",
    symbol: "$",
    capital: "Kralendijk",
    continent: "North America",
  },
  {
    iso: "br",
    code: "BRL",
    symbol: "R$",
    capital: "Brasília",
    continent: "South America",
  },
  {
    iso: "bs",
    code: "BSD",
    symbol: "B$",
    capital: "Nassau",
    continent: "North America",
  },
  {
    iso: "bt",
    code: "BTN",
    symbol: "Nu.",
    capital: "Thimphu",
    continent: "Asia",
  },
  {
    iso: "bv",
    code: "NOK",
    symbol: "kr",
    capital: "",
    continent: "Antarctica",
  },
  {
    iso: "bw",
    code: "BWP",
    symbol: "P",
    capital: "Gaborone",
    continent: "Africa",
  },
  {
    iso: "by",
    code: "BYR",
    symbol: "Br",
    capital: "Minsk",
    continent: "Europe",
  },
  {
    iso: "bz",
    code: "BZD",
    symbol: "$",
    capital: "Belmopan",
    continent: "North America",
  },
  {
    iso: "ca",
    code: "CAD",
    symbol: "$",
    capital: "Ottawa",
    continent: "North America",
  },
  {
    iso: "cc",
    code: "AUD",
    symbol: "$",
    capital: "West Island",
    continent: "Asia",
  },
  {
    iso: "cd",
    code: "CDF",
    symbol: "F",
    capital: "Kinshasa",
    continent: "Africa",
  },
  {
    iso: "cf",
    code: "XAF",
    symbol: "FCFA",
    capital: "Bangui",
    continent: "Africa",
  },
  {
    iso: "cg",
    code: "XAF",
    symbol: "FCFA",
    capital: "Brazzaville",
    continent: "Africa",
  },
  {
    iso: "ch",
    code: "CHF",
    symbol: "Fr.",
    capital: "Bern",
    continent: "Europe",
  },
  {
    iso: "ci",
    code: "XOF",
    symbol: "CFA",
    capital: "Yamoussoukro",
    continent: "Africa",
  },
  {
    iso: "ck",
    code: "NZD",
    symbol: "$",
    capital: "Avarua",
    continent: "Oceania",
  },
  {
    iso: "cl",
    code: "CLP",
    symbol: "$",
    capital: "Santiago",
    continent: "South America",
  },
  {
    iso: "cm",
    code: "XAF",
    symbol: "FCFA",
    capital: "Yaoundé",
    continent: "Africa",
  },
  {
    iso: "cn",
    code: "CNY",
    symbol: "¥",
    capital: "Beijing",
    continent: "Asia",
  },
  {
    iso: "co",
    code: "COP",
    symbol: "Col$",
    capital: "Bogotá",
    continent: "South America",
  },
  {
    iso: "cr",
    code: "CRC",
    symbol: "₡",
    capital: "San José",
    continent: "North America",
  },
  {
    iso: "cv",
    code: "CVE",
    symbol: "Esc",
    capital: "Praia",
    continent: "Africa",
  },
  {
    iso: "cw",
    code: "ANG",
    symbol: "NAƒ",
    capital: "Willemstad",
    continent: "North America",
  },
  {
    iso: "cx",
    code: "AUD",
    symbol: "$",
    capital: "Flying Fish Cove",
    continent: "Asia",
  },
  {
    iso: "cy",
    code: "EUR",
    symbol: "€",
    capital: "Nicosia",
    continent: "Europe",
  },
  {
    iso: "cz",
    code: "CZK",
    symbol: "Kč",
    capital: "Prague",
    continent: "Europe",
  },
  {
    iso: "de",
    code: "EUR",
    symbol: "€",
    capital: "Berlin",
    continent: "Europe",
  },
  {
    iso: "dj",
    code: "DJF",
    symbol: "Fdj",
    capital: "Djibouti",
    continent: "Africa",
  },
  {
    iso: "dk",
    code: "DKK",
    symbol: "Kr",
    capital: "Copenhagen",
    continent: "Europe",
  },
  {
    iso: "dm",
    code: "XCD",
    symbol: "$",
    capital: "Roseau",
    continent: "North America",
  },
  {
    iso: "do",
    code: "DOP",
    symbol: "RD$",
    capital: "Santo Domingo",
    continent: "North America",
  },
  {
    iso: "dz",
    code: "DZD",
    symbol: "دج",
    capital: "Algiers",
    continent: "Africa",
  },
  {
    iso: "ec",
    code: "USD",
    symbol: "$",
    capital: "Quito",
    continent: "South America",
  },
  {
    iso: "ee",
    code: "EUR",
    symbol: "€",
    capital: "Tallinn",
    continent: "Europe",
  },
  {
    iso: "eg",
    code: "EGP",
    symbol: "E£",
    capital: "Cairo",
    continent: "Africa",
  },
  {
    iso: "eh",
    code: "MAD",
    symbol: "MAD",
    capital: "Laâyoune / El Aaiún",
    continent: "Africa",
  },
  {
    iso: "er",
    code: "ERN",
    symbol: "Nfa",
    capital: "Asmara",
    continent: "Africa",
  },
  {
    iso: "es",
    code: "EUR",
    symbol: "€",
    capital: "Madrid",
    continent: "Europe",
  },
  {
    iso: "et",
    code: "ETB",
    symbol: "Br",
    capital: "Addis Ababa",
    continent: "Africa",
  },
  {
    iso: "fi",
    code: "EUR",
    symbol: "€",
    capital: "Helsinki",
    continent: "Europe",
  },
  {
    iso: "fj",
    code: "FJD",
    symbol: "FJ$",
    capital: "Suva",
    continent: "Oceania",
  },
  {
    iso: "fk",
    code: "FKP",
    symbol: "£",
    capital: "Stanley",
    continent: "South America",
  },
  {
    iso: "fm",
    code: "USD",
    symbol: "$",
    capital: "Palikir",
    continent: "Oceania",
  },
  {
    iso: "fo",
    code: "DKK",
    symbol: "Kr",
    capital: "Tórshavn",
    continent: "Europe",
  },
  {
    iso: "fr",
    code: "EUR",
    symbol: "€",
    capital: "Paris",
    continent: "Europe",
  },
  {
    iso: "ga",
    code: "XAF",
    symbol: "FCFA",
    capital: "Libreville",
    continent: "Africa",
  },
  {
    iso: "gb",
    code: "GBP",
    symbol: "£",
    capital: "London",
    continent: "Europe",
  },
  {
    iso: "gd",
    code: "XCD",
    symbol: "$",
    capital: "St. George's",
    continent: "North America",
  },
  {
    iso: "ge",
    code: "GEL",
    symbol: "GEL",
    capital: "Tbilisi",
    continent: "Asia",
  },
  {
    iso: "gf",
    code: "EUR",
    symbol: "€",
    capital: "Cayenne",
    continent: "South America",
  },
  {
    iso: "gg",
    code: "GBP",
    symbol: "£",
    capital: "St Peter Port",
    continent: "Europe",
  },
  {
    iso: "gh",
    code: "GHS",
    symbol: "Gh₵",
    capital: "Accra",
    continent: "Africa",
  },
  {
    iso: "gi",
    code: "GIP",
    symbol: "£",
    capital: "Gibraltar",
    continent: "Europe",
  },
  {
    iso: "gl",
    code: "DKK",
    symbol: "Kr",
    capital: "Nuuk",
    continent: "North America",
  },
  {
    iso: "gm",
    code: "GMD",
    symbol: "D",
    capital: "Bathurst",
    continent: "Africa",
  },
  {
    iso: "gn",
    code: "GNF",
    symbol: "FG",
    capital: "Conakry",
    continent: "Africa",
  },
  {
    iso: "gp",
    code: "EUR",
    symbol: "€",
    capital: "Basse-Terre",
    continent: "North America",
  },
  {
    iso: "gq",
    code: "XAF",
    symbol: "FCFA",
    capital: "Malabo",
    continent: "Africa",
  },
  {
    iso: "gr",
    code: "EUR",
    symbol: "€",
    capital: "Athens",
    continent: "Europe",
  },
  {
    iso: "gs",
    code: "GBP",
    symbol: "£",
    capital: "Grytviken",
    continent: "Antarctica",
  },
  {
    iso: "gt",
    code: "GTQ",
    symbol: "Q",
    capital: "Guatemala City",
    continent: "North America",
  },
  {
    iso: "gu",
    code: "USD",
    symbol: "$",
    capital: "Hagåtña",
    continent: "Oceania",
  },
  {
    iso: "gw",
    code: "XOF",
    symbol: "CFA",
    capital: "Bissau",
    continent: "Africa",
  },
  {
    iso: "gy",
    code: "GYD",
    symbol: "GY$",
    capital: "Georgetown",
    continent: "South America",
  },
  {
    iso: "hk",
    code: "HKD",
    symbol: "HK$",
    capital: "Hong Kong",
    continent: "Asia",
  },
  {
    iso: "hm",
    code: "AUD",
    symbol: "$",
    capital: "",
    continent: "Antarctica",
  },
  {
    iso: "hn",
    code: "HNL",
    symbol: "L",
    capital: "Tegucigalpa",
    continent: "North America",
  },
  {
    iso: "hr",
    code: "HRK",
    symbol: "kn",
    capital: "Zagreb",
    continent: "Europe",
  },
  {
    iso: "ht",
    code: "HTG",
    symbol: "G",
    capital: "Port-au-Prince",
    continent: "North America",
  },
  {
    iso: "hu",
    code: "HUF",
    symbol: "Ft",
    capital: "Budapest",
    continent: "Europe",
  },
  {
    iso: "id",
    code: "IDR",
    symbol: "Rp",
    capital: "Jakarta",
    continent: "Asia",
  },
  {
    iso: "ie",
    code: "EUR",
    symbol: "€",
    capital: "Dublin",
    continent: "Europe",
  },
  {
    iso: "il",
    code: "ILS",
    symbol: "₪",
    capital: "",
    continent: "Asia",
  },
  {
    iso: "im",
    code: "GBP",
    symbol: "£",
    capital: "Douglas",
    continent: "Europe",
  },
  {
    iso: "in",
    code: "INR",
    symbol: "₹",
    capital: "New Delhi",
    continent: "Asia",
  },
  {
    iso: "io",
    code: "USD",
    symbol: "$",
    capital: "",
    continent: "Asia",
  },
  {
    iso: "iq",
    code: "IQD",
    symbol: "ع.د",
    capital: "Baghdad",
    continent: "Asia",
  },
  {
    iso: "ir",
    code: "IRR",
    symbol: "IRR",
    capital: "Tehran",
    continent: "Asia",
  },
  {
    iso: "is",
    code: "ISK",
    symbol: "kr",
    capital: "Reykjavik",
    continent: "Europe",
  },
  {
    iso: "it",
    code: "EUR",
    symbol: "€",
    capital: "Rome",
    continent: "Europe",
  },
  {
    iso: "je",
    code: "GBP",
    symbol: "£",
    capital: "Saint Helier",
    continent: "Europe",
  },
  {
    iso: "jm",
    code: "JMD",
    symbol: "J$",
    capital: "Kingston",
    continent: "North America",
  },
  {
    iso: "jo",
    code: "JOD",
    symbol: "JOD",
    capital: "Amman",
    continent: "Asia",
  },
  {
    iso: "jp",
    code: "JPY",
    symbol: "¥",
    capital: "Tokyo",
    continent: "Asia",
  },
  {
    iso: "ke",
    code: "KES",
    symbol: "KSh",
    capital: "Nairobi",
    continent: "Africa",
  },
  {
    iso: "kg",
    code: "KGS",
    symbol: "Лв",
    capital: "Bishkek",
    continent: "Asia",
  },
  {
    iso: "kh",
    code: "KHR",
    symbol: "៛",
    capital: "Phnom Penh",
    continent: "Asia",
  },
  {
    iso: "ki",
    code: "AUD",
    symbol: "$",
    capital: "Tarawa",
    continent: "Oceania",
  },
  {
    iso: "km",
    code: "KMF",
    symbol: "KMF",
    capital: "Moroni",
    continent: "Africa",
  },
  {
    iso: "kn",
    code: "XCD",
    symbol: "$",
    capital: "Basseterre",
    continent: "North America",
  },
  {
    iso: "kp",
    code: "KPW",
    symbol: "W",
    capital: "Pyongyang",
    continent: "Asia",
  },
  {
    iso: "kr",
    code: "KRW",
    symbol: "W",
    capital: "Seoul",
    continent: "Asia",
  },
  {
    iso: "kw",
    code: "KWD",
    symbol: "KWD",
    capital: "Kuwait City",
    continent: "Asia",
  },
  {
    iso: "ky",
    code: "KYD",
    symbol: "KY$",
    capital: "George Town",
    continent: "North America",
  },
  {
    iso: "kz",
    code: "KZT",
    symbol: "T",
    capital: "Astana",
    continent: "Asia",
  },
  {
    iso: "la",
    code: "LAK",
    symbol: "KN",
    capital: "Vientiane",
    continent: "Asia",
  },
  {
    iso: "lb",
    code: "LBP",
    symbol: "ل.ل.",
    capital: "Beirut",
    continent: "Asia",
  },
  {
    iso: "lc",
    code: "XCD",
    symbol: "$",
    capital: "Castries",
    continent: "North America",
  },
  {
    iso: "li",
    code: "CHF",
    symbol: "Fr.",
    capital: "Vaduz",
    continent: "Europe",
  },
  {
    iso: "lk",
    code: "LKR",
    symbol: "Rs",
    capital: "Colombo",
    continent: "Asia",
  },
  {
    iso: "lr",
    code: "LRD",
    symbol: "L$",
    capital: "Monrovia",
    continent: "Africa",
  },
  {
    iso: "ls",
    code: "LSL",
    symbol: "M",
    capital: "Maseru",
    continent: "Africa",
  },
  {
    iso: "lt",
    code: "EUR",
    symbol: "€",
    capital: "Vilnius",
    continent: "Europe",
  },
  {
    iso: "lu",
    code: "EUR",
    symbol: "€",
    capital: "Luxembourg",
    continent: "Europe",
  },
  {
    iso: "lv",
    code: "EUR",
    symbol: "€",
    capital: "Riga",
    continent: "Europe",
  },
  {
    iso: "ly",
    code: "LYD",
    symbol: "LD",
    capital: "Tripoli",
    continent: "Africa",
  },
  {
    iso: "ma",
    code: "MAD",
    symbol: "MAD",
    capital: "Rabat",
    continent: "Africa",
  },
  {
    iso: "mc",
    code: "EUR",
    symbol: "€",
    capital: "Monaco",
    continent: "Europe",
  },
  {
    iso: "md",
    code: "MDL",
    symbol: "MDL",
    capital: "Chişinău",
    continent: "Europe",
  },
  {
    iso: "me",
    code: "EUR",
    symbol: "€",
    capital: "Podgorica",
    continent: "Europe",
  },
  {
    iso: "mf",
    code: "EUR",
    symbol: "€",
    capital: "Marigot",
    continent: "North America",
  },
  {
    iso: "mg",
    code: "MGA",
    symbol: "FMG",
    capital: "Antananarivo",
    continent: "Africa",
  },
  {
    iso: "mh",
    code: "USD",
    symbol: "$",
    capital: "Majuro",
    continent: "Oceania",
  },
  {
    iso: "mk",
    code: "MKD",
    symbol: "MKD",
    capital: "Skopje",
    continent: "Europe",
  },
  {
    iso: "ml",
    code: "XOF",
    symbol: "CFA",
    capital: "Bamako",
    continent: "Africa",
  },
  {
    iso: "mm",
    code: "MMK",
    symbol: "K",
    capital: "Naypyitaw",
    continent: "Asia",
  },
  {
    iso: "mn",
    code: "MNT",
    symbol: "₮",
    capital: "Ulan Bator",
    continent: "Asia",
  },
  {
    iso: "mo",
    code: "MOP",
    symbol: "P",
    capital: "Macao",
    continent: "Asia",
  },
  {
    iso: "mp",
    code: "USD",
    symbol: "$",
    capital: "Saipan",
    continent: "Oceania",
  },
  {
    iso: "mq",
    code: "EUR",
    symbol: "€",
    capital: "Fort-de-France",
    continent: "North America",
  },
  {
    iso: "mr",
    code: "MRO",
    symbol: "UM",
    capital: "Nouakchott",
    continent: "Africa",
  },
  {
    iso: "ms",
    code: "XCD",
    symbol: "$",
    capital: "Plymouth",
    continent: "North America",
  },
  {
    iso: "mt",
    code: "EUR",
    symbol: "€",
    capital: "Valletta",
    continent: "Europe",
  },
  {
    iso: "mu",
    code: "MUR",
    symbol: "Rs",
    capital: "Port Louis",
    continent: "Africa",
  },
  {
    iso: "mv",
    code: "MVR",
    symbol: "Rf",
    capital: "Malé",
    continent: "Asia",
  },
  {
    iso: "mw",
    code: "MWK",
    symbol: "MK",
    capital: "Lilongwe",
    continent: "Africa",
  },
  {
    iso: "mx",
    code: "MXN",
    symbol: "$",
    capital: "Mexico City",
    continent: "North America",
  },
  {
    iso: "my",
    code: "MYR",
    symbol: "RM",
    capital: "Kuala Lumpur",
    continent: "Asia",
  },
  {
    iso: "na",
    code: "NAD",
    symbol: "N$",
    capital: "Windhoek",
    continent: "Africa",
  },
  {
    iso: "nc",
    code: "XPF",
    symbol: "F",
    capital: "Noumea",
    continent: "Oceania",
  },
  {
    iso: "ne",
    code: "XOF",
    symbol: "CFA",
    capital: "Niamey",
    continent: "Africa",
  },
  {
    iso: "nf",
    code: "AUD",
    symbol: "$",
    capital: "Kingston",
    continent: "Oceania",
  },
  {
    iso: "ng",
    code: "NGN",
    symbol: "₦",
    capital: "Abuja",
    continent: "Africa",
  },
  {
    iso: "ni",
    code: "NIO",
    symbol: "C$",
    capital: "Managua",
    continent: "North America",
  },
  {
    iso: "nl",
    code: "EUR",
    symbol: "€",
    capital: "Amsterdam",
    continent: "Europe",
  },
  {
    iso: "no",
    code: "NOK",
    symbol: "kr",
    capital: "Oslo",
    continent: "Europe",
  },
  {
    iso: "np",
    code: "NPR",
    symbol: "NRs",
    capital: "Kathmandu",
    continent: "Asia",
  },
  {
    iso: "nr",
    code: "AUD",
    symbol: "$",
    capital: "Yaren",
    continent: "Oceania",
  },
  {
    iso: "nu",
    code: "NZD",
    symbol: "$",
    capital: "Alofi",
    continent: "Oceania",
  },
  {
    iso: "nz",
    code: "NZD",
    symbol: "$",
    capital: "Wellington",
    continent: "Oceania",
  },
  {
    iso: "om",
    code: "OMR",
    symbol: "OMR",
    capital: "Muscat",
    continent: "Asia",
  },
  {
    iso: "pa",
    code: "PAB",
    symbol: "B/.",
    capital: "Panama City",
    continent: "North America",
  },
  {
    iso: "pe",
    code: "PEN",
    symbol: "S/.",
    capital: "Lima",
    continent: "South America",
  },
  {
    iso: "pf",
    code: "XPF",
    symbol: "F",
    capital: "Papeete",
    continent: "Oceania",
  },
  {
    iso: "pg",
    code: "PGK",
    symbol: "K",
    capital: "Port Moresby",
    continent: "Oceania",
  },
  {
    iso: "ph",
    code: "PHP",
    symbol: "₱",
    capital: "Manila",
    continent: "Asia",
  },
  {
    iso: "pk",
    code: "PKR",
    symbol: "Rs.",
    capital: "Islamabad",
    continent: "Asia",
  },
  {
    iso: "pl",
    code: "PLN",
    symbol: "zł",
    capital: "Warsaw",
    continent: "Europe",
  },
  {
    iso: "pm",
    code: "EUR",
    symbol: "€",
    capital: "Saint-Pierre",
    continent: "North America",
  },
  {
    iso: "pn",
    code: "NZD",
    symbol: "$",
    capital: "Adamstown",
    continent: "Oceania",
  },
  {
    iso: "pr",
    code: "USD",
    symbol: "$",
    capital: "San Juan",
    continent: "North America",
  },
  {
    iso: "ps",
    code: "ILS",
    symbol: "₪",
    capital: "",
    continent: "Asia",
  },
  {
    iso: "pt",
    code: "EUR",
    symbol: "€",
    capital: "Lisbon",
    continent: "Europe",
  },
  {
    iso: "pw",
    code: "USD",
    symbol: "$",
    capital: "Melekeok",
    continent: "Oceania",
  },
  {
    iso: "py",
    code: "PYG",
    symbol: "₲",
    capital: "Asunción",
    continent: "South America",
  },
  {
    iso: "qa",
    code: "QAR",
    symbol: "QR",
    capital: "Doha",
    continent: "Asia",
  },
  {
    iso: "re",
    code: "EUR",
    symbol: "€",
    capital: "Saint-Denis",
    continent: "Africa",
  },
  {
    iso: "ro",
    code: "RON",
    symbol: "L",
    capital: "Bucharest",
    continent: "Europe",
  },
  {
    iso: "rs",
    code: "RSD",
    symbol: "din.",
    capital: "Belgrade",
    continent: "Europe",
  },
  {
    iso: "ru",
    code: "RUB",
    symbol: "R",
    capital: "Moscow",
    continent: "Europe",
  },
  {
    iso: "sa",
    code: "SAR",
    symbol: "SR",
    capital: "Riyadh",
    continent: "Asia",
  },
  {
    iso: "sb",
    code: "SBD",
    symbol: "Si$",
    capital: "Honiara",
    continent: "Oceania",
  },
  {
    iso: "sc",
    code: "SCR",
    symbol: "SR",
    capital: "Victoria",
    continent: "Africa",
  },
  {
    iso: "sd",
    code: "SDG",
    symbol: "SDG",
    capital: "Khartoum",
    continent: "Africa",
  },
  {
    iso: "se",
    code: "SEK",
    symbol: "kr",
    capital: "Stockholm",
    continent: "Europe",
  },
  {
    iso: "sg",
    code: "SGD",
    symbol: "S$",
    capital: "Singapore",
    continent: "Asia",
  },
  {
    iso: "sh",
    code: "SHP",
    symbol: "£",
    capital: "Jamestown",
    continent: "Africa",
  },
  {
    iso: "si",
    code: "EUR",
    symbol: "€",
    capital: "Ljubljana",
    continent: "Europe",
  },
  {
    iso: "sj",
    code: "NOK",
    symbol: "kr",
    capital: "Longyearbyen",
    continent: "Europe",
  },
  {
    iso: "sk",
    code: "EUR",
    symbol: "€",
    capital: "Bratislava",
    continent: "Europe",
  },
  {
    iso: "sl",
    code: "SLL",
    symbol: "Le",
    capital: "Freetown",
    continent: "Africa",
  },
  {
    iso: "sm",
    code: "EUR",
    symbol: "€",
    capital: "San Marino",
    continent: "Europe",
  },
  {
    iso: "sn",
    code: "XOF",
    symbol: "CFA",
    capital: "Dakar",
    continent: "Africa",
  },
  {
    iso: "so",
    code: "SOS",
    symbol: "Sh.",
    capital: "Mogadishu",
    continent: "Africa",
  },
  {
    iso: "sr",
    code: "SRD",
    symbol: "$",
    capital: "Paramaribo",
    continent: "South America",
  },
  {
    iso: "sv",
    code: "USD",
    symbol: "$",
    capital: "San Salvador",
    continent: "North America",
  },
  {
    iso: "sx",
    code: "ANG",
    symbol: "NAƒ",
    capital: "Philipsburg",
    continent: "North America",
  },
  {
    iso: "sy",
    code: "SYP",
    symbol: "LS",
    capital: "Damascus",
    continent: "Asia",
  },
  {
    iso: "sz",
    code: "SZL",
    symbol: "E",
    capital: "Mbabane",
    continent: "Africa",
  },
  {
    iso: "tc",
    code: "USD",
    symbol: "$",
    capital: "Cockburn Town",
    continent: "North America",
  },
  {
    iso: "td",
    code: "XAF",
    symbol: "FCFA",
    capital: "N'Djamena",
    continent: "Africa",
  },
  {
    iso: "tf",
    code: "EUR",
    symbol: "€",
    capital: "Port-aux-Français",
    continent: "Antarctica",
  },
  {
    iso: "tg",
    code: "XOF",
    symbol: "CFA",
    capital: "Lomé",
    continent: "Africa",
  },
  {
    iso: "th",
    code: "THB",
    symbol: "฿",
    capital: "Bangkok",
    continent: "Asia",
  },
  {
    iso: "tj",
    code: "TJS",
    symbol: "TJS",
    capital: "Dushanbe",
    continent: "Asia",
  },
  {
    iso: "tk",
    code: "NZD",
    symbol: "$",
    capital: "",
    continent: "Oceania",
  },
  {
    iso: "tl",
    code: "USD",
    symbol: "$",
    capital: "Dili",
    continent: "Oceania",
  },
  {
    iso: "tm",
    code: "TMT",
    symbol: "m",
    capital: "Ashgabat",
    continent: "Asia",
  },
  {
    iso: "tn",
    code: "TND",
    symbol: "DT",
    capital: "Tunis",
    continent: "Africa",
  },
  {
    iso: "tr",
    code: "TRY",
    symbol: "TRY",
    capital: "Ankara",
    continent: "Asia",
  },
  {
    iso: "tt",
    code: "TTD",
    symbol: "TT$",
    capital: "Port of Spain",
    continent: "North America",
  },
  {
    iso: "tv",
    code: "AUD",
    symbol: "$",
    capital: "Funafuti",
    continent: "Oceania",
  },
  {
    iso: "tw",
    code: "TWD",
    symbol: "NT$",
    capital: "Taipei",
    continent: "Asia",
  },
  {
    iso: "tz",
    code: "TZS",
    symbol: "TZS",
    capital: "Dodoma",
    continent: "Africa",
  },
  {
    iso: "ua",
    code: "UAH",
    symbol: "UAH",
    capital: "Kiev",
    continent: "Europe",
  },
  {
    iso: "ug",
    code: "UGX",
    symbol: "USh",
    capital: "Kampala",
    continent: "Africa",
  },
  {
    iso: "um",
    code: "USD",
    symbol: "$",
    capital: "",
    continent: "Oceania",
  },
  {
    iso: "us",
    code: "USD",
    symbol: "$",
    capital: "Washington",
    continent: "North America",
  },
  {
    iso: "uy",
    code: "UYU",
    symbol: "$U",
    capital: "Montevideo",
    continent: "South America",
  },
  {
    iso: "uz",
    code: "UZS",
    symbol: "UZS",
    capital: "Tashkent",
    continent: "Asia",
  },
  {
    iso: "va",
    code: "EUR",
    symbol: "€",
    capital: "Vatican City",
    continent: "Europe",
  },
  {
    iso: "vc",
    code: "XCD",
    symbol: "$",
    capital: "Kingstown",
    continent: "North America",
  },
  {
    iso: "vg",
    code: "USD",
    symbol: "$",
    capital: "Road Town",
    continent: "North America",
  },
  {
    iso: "vi",
    code: "USD",
    symbol: "$",
    capital: "Charlotte Amalie",
    continent: "North America",
  },
  {
    iso: "vn",
    code: "VND",
    symbol: "₫",
    capital: "Hanoi",
    continent: "Asia",
  },
  {
    iso: "vu",
    code: "VUV",
    symbol: "VT",
    capital: "Port Vila",
    continent: "Oceania",
  },
  {
    iso: "wf",
    code: "XPF",
    symbol: "F",
    capital: "Mata-Utu",
    continent: "Oceania",
  },
  {
    iso: "ws",
    code: "WST",
    symbol: "WS$",
    capital: "Apia",
    continent: "Oceania",
  },
  {
    iso: "xk",
    code: "EUR",
    symbol: "€",
    capital: "Pristina",
    continent: "Europe",
  },
  {
    iso: "ye",
    code: "YER",
    symbol: "YER",
    capital: "Sanaa",
    continent: "Asia",
  },
  {
    iso: "yt",
    code: "EUR",
    symbol: "€",
    capital: "Mamoudzou",
    continent: "Africa",
  },
  {
    iso: "za",
    code: "ZAR",
    symbol: "R",
    capital: "Pretoria",
    continent: "Africa",
  },
];
