export default {
  singular: "event",
  type: "events",
  group: "events",
  image: "test.jpg",
  color: "#17345b",
  title: "upcoming-events",
  create: "create-an-event",
  attendance: ["online", "in-person"],
  sort: [
    "latest-events",
    "event-date-up",
    "event-date-down",
    "ad-date-ascending",
    "ad-date-descending",
    "most-viewed",
  ],
  desc: "events-desc",
  cat: [
    "career-business",
    "charities",
    "conferences-seminar",
    "dance",
    "fashion-beauty",
    "festival-fairs",
    "film",
    "food-drink",
    "health-wellness",
    "kids-family",
    "language-culture",
    "lectures-books",
    "movements",
    "music",
    "nightlife",
    "performing-arts",
    "photography",
    "science-technology",
    "sports-fitness",
    "visual-arts",
    "class",
    "party",
    "attraction",
    "convention",
    "expo",
    "gala",
    "networking",
    "race",
    "rally",
    "retreat",
    "screening",
    "tournament",
    "tour",
    "sports-competetion",
    "firework",
  ],
};
